# WS2012R2 image with April WMF5.0
os: unstable

# clone directory
clone_folder: c:\projects\Archive-Module
 
# Install Pester
install: 
    - cinst -y pester
    
build: false

# Run Pester tests and store the results
test_script:
    - SET PATH=c:\Program Files\WindowsPowerShell\Modules\;%PATH%;
    - ps: |
        copy "C:\projects\Archive-Module\Microsoft.PowerShell.Archive" "$Env:ProgramFiles\WindowsPowerShell\Modules\" -Recurse -Force
        $testResultsFile = ".\EngineTestResults.xml"
        $testResults = Invoke-Pester -Script "C:\projects\Archive-Module\Tests" -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($testResults.FailedCount -gt 0) { 
            throw "$($testResults.FailedCount) tests failed."
        }